server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/open_nft?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    generate-ddl: true
    database-platform: 
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  thymeleaf:
    cache: false
  redis:
    port: 6379
    host: localhost
    timeout: 5000 #连接超时时间
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
redisson:
  singleServerConfig:
    address: 127.0.0.1:6379
jetcache:
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
  remote:
    default:
      type: redis.lettuce
      keyConvertor: fastjson
      uri: redis://@127.0.0.1:6379/
# Sa-Token配置
sa-token: 
    # token名称 (同时也是cookie名称)
    token-name: member_token
    # token有效期，单位s 默认30天, -1代表永不过期 
    timeout: 2592000
    is-read-cookie: true
    is-read-head: true
    # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
    activity-timeout: -1
           # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录) 
    is-concurrent: true
            # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token) 
    is-share: false
    # token风格
    token-style: random-64
            # 是否输出操作日志 
    is-log: false